Add Landau-Rohrbach
marhei/TrainCompany-Data pull request #113
Opened 2022-06-27 18:24 UTC by f2k1de

2022-06-27 18:43 UTC, marhei requested changes
Bitte rebasen! Dein PR löscht ganz viele Daten raus…

2022-06-27 18:44 UTC, f2k1de commented
Interessant… Bei mir kommt no conflicts mit base branch und wenn ich auf files changes gehe sehe ich auch nur Zufügungen aber keine rauslöschungen von irgendwas.

2022-06-27 18:46 UTC, marhei commented
Ich schau mir das im Zweifel morgen noch mal am Computer an. 
![image](https://user-images.githubusercontent.com/10304183/176013411-8d9a8838-d7b8-4900-a0c0-731e669e9156.png)

2022-06-28 02:14 UTC, marhei approved these changes

2022-06-28 02:14 UTC, merged