Add Osnabrück-Hengelo
marhei/TrainCompany-Data pull request #121
Opened 2022-06-28 13:23 UTC by f2k1de

2022-06-28 13:24 UTC, f2k1de commented
Fahrzeug + TrainEquipment für NL kommt gleich auch noch

2022-06-28 13:29 UTC, C1710 commented
Ich wollte gerade anfangen mit Münster - Enschede :D

2022-06-28 19:08 UTC, f2k1de commented
Wikipedia Artikel für Gleise + Auf OSM messen. Nicht Optimal aber offizielle Daten habe ich bisher keine gefunden.

2022-06-28 19:09 UTC, C1710 commented
> Wikipedia Artikel für Gleise + Auf OSM messen. Nicht Optimal aber offizielle Daten habe ich bisher keine gefunden.  

Okay, so hab ich's auch gemacht 😂

2022-06-28 19:28 UTC, C1710 requested changes
Routen fehlen noch :D (nicht, dass das gleich so gemergt wird)

2022-06-28 19:30 UTC, C1710 commented
Würde es wohl Sinn ergeben, den Flirt 3XL als NL-tauglich zu kennzeichnen?
Passt zwar nicht 100%, aber weitestgehend...

2022-06-29 07:11 UTC, marhei approved these changes

2022-06-29 07:11 UTC, merged