Add München-Rosenheim
marhei/TrainCompany-Data pull request #163
Opened 2022-06-30 10:46 UTC by f2k1de

2022-06-30 11:23 UTC, C1710 commented
Erstellst du inzwischen auch automatisiert PRs? :D

2022-06-30 11:24 UTC, C1710 approved these changes

2022-06-30 15:34 UTC, marhei requested changes

2022-07-01 11:17 UTC, C1710 commented
Ich wollte eigentlich einen PR mit den ergänzten `maxSpeed`s machen, sorry....

2022-07-01 12:01 UTC, marhei approved these changes

2022-07-01 12:01 UTC, merged