Speisewagen
marhei/TrainCompany-Data pull request #199
Opened 2022-07-04 18:23 UTC by embix

- +Cargotype: Bewirtungsplätze in Speisewagen/Buffetwagen/Bordbistro
- +3 passende Wagontypen
- Bewirtungsplätze in ICEs hinzugefügt
- einige Ausschreibungen für ICE/EC/IC um Anforderung Bewirtungsplätze erweitert

Anmerkung: 
- Beim ICE1 wurden vom WSmz nur die 24 Restaurantsitzplätze berücksichtigt, nicht die Stehplätze im Bistro. 
- Bistrokapazität TGV 2N2 ist mir nicht bekannt.
- fortlaufende ids 37,38,39 verwendet (stand letzter pull)
- Follow-Up Idee: McTrain Direktvergabe

2022-07-04 21:43 UTC, marhei requested changes
Gute Idee nur zu hoher Faktor. Würde eher in Richtung 0.05 gehen…

2022-07-04 21:43 UTC, marhei commented on Capacity.json
> +			"exchangeFactor": 0.5
Bisschen sehr hoher Faktor? Meinst du wirklich, dass die Hälfte aller Fahrgäste einen Platz im Speisewagen wollen?

2022-07-05 07:12 UTC, embix commented on Capacity.json
> +			"exchangeFactor": 0.5
Stimmt, 20% wäre evtl. schon viel. Bei Langstrecke vielleicht sogar okay, aber die meisten fahren ja nur einen Teil der Strecke mit und da ist das Interesse auch geringer. 5-10% klingt sinnvoll.

2022-07-05 08:27 UTC, marhei approved these changes

2022-07-05 08:27 UTC, merged