Added Eanos-x 059
marhei/TrainCompany-Data pull request #278
Opened 2022-07-13 14:03 UTC by ChillLP

2022-07-13 15:31 UTC, ChillLP commented
🥺

2022-07-13 15:43 UTC, marhei requested changes

2022-07-13 15:43 UTC, marhei commented on Train.json
> +				{"name": "coal", "value": 30}
Entweder oder aber nicht beides…

2022-07-13 15:48 UTC, ChillLP commented on Train.json
> +				{"name": "coal", "value": 30}
Einer für kohle einer Für holz?

2022-07-13 16:25 UTC, marhei commented on Train.json
> +				{"name": "coal", "value": 30}
Wieso sollte man sich einen teureren Wagen mit weniger Kapazität kaufen?

2022-07-13 16:35 UTC, ChillLP commented on Train.json
> +				{"name": "coal", "value": 30}
Der sinn desssen war ja einen wagen zu haben der beides kann, deswegen ja auch teurer.

2022-07-13 16:42 UTC, marhei commented on Train.json
> +				{"name": "coal", "value": 30}
Naja gut, aber das geht wie gesagt aktuell technisch nicht.

2022-07-13 16:44 UTC, ChillLP commented on Train.json
> +				{"name": "coal", "value": 30}
Jut, dann Draft until possible

2022-08-02 07:19 UTC, marhei approved these changes

2022-08-02 07:19 UTC, merged