Add LGV Sud Europe Atlantique
marhei/TrainCompany-Data pull request #295
Opened 2022-07-14 13:35 UTC by f2k1de

2022-07-14 16:32 UTC, f2k1de commented
Aber Tours ist doch neben der LGV und gehört dann eher zur Bahnstrecke Paris–Bordeaux?

2022-07-14 17:38 UTC, marhei commented
Tours war das ehemalige Ende der LGV.

2022-07-14 19:42 UTC, marhei requested changes
Test schlägt bei über 300 km Strecke fehl und ich halte das auch für einen zu langen Streckenabschnitt… Eine Anbindung von Tour würde das Problem lösen

2022-07-15 07:58 UTC, marhei approved these changes

2022-07-15 07:58 UTC, merged