Add wuerttemberg-baden
marhei/TrainCompany-Data pull request #58
Opened 2022-06-24 13:38 UTC by f2k1de

2022-06-24 14:06 UTC, marhei commented
Grundsätzlich gut, aber bitte mehr Unterwegsbahnhöfe! Streckenabschnitte am besten nie länger als 20-30 km (außer SFS)

2022-06-24 15:18 UTC, marhei requested changes
Zwischen RK und RO weiterhin ÜBER 70 km Strecke. Raststatt, Baden-Baden und Appenweier auf jeden Fall mindestens noch.

2022-06-24 22:00 UTC, marhei requested changes
Falsches Ril100 für Rastatt.

2022-06-25 19:24 UTC, marhei approved these changes

2022-06-25 19:25 UTC, merged

2022-06-25 19:58 UTC, C1710 commented
Mh, ich glaube, da stimmt was mit den Positionen der Haltepunkte nicht

![Übersicht der Region](https://user-images.githubusercontent.com/10349490/175788826-2366d17c-01b0-47e7-b09c-d9c51290dd02.png)