Add V100 and B3yg54 for heritage reasons
marhei/TrainCompany-Data pull request #66
Opened 2022-06-25 08:06 UTC by bjoernma

2022-06-25 19:29 UTC, marhei requested changes
Checks fehlgeschlagen

2022-06-26 10:11 UTC, embix reviewed
1. fixed schema so linter check should pass
2. (optional) suggested non-ambiguous naming

2022-06-26 10:11 UTC, embix commented on Train.json
> +
Der linter meint, du solltest das object noch abschließen.

```suggestion
		},
```

2022-06-26 11:02 UTC, bjoernma commented
Thanks for the changes. Probably it should work now...

2022-06-26 11:16 UTC, marhei approved these changes

2022-06-26 11:16 UTC, merged