Tippfehler station.json
marhei/TrainCompany-Data pull request #73
Opened 2022-06-25 16:11 UTC by bjoernma

2022-06-25 19:29 UTC, marhei requested changes
Checks fehlgeschlagen

2022-06-25 19:54 UTC, C1710 commented
Es ist eine neue Zeile am Ende.

2022-06-26 10:25 UTC, C1710 commented on Station.json
> +}
Die hier muss weg

2022-06-26 11:09 UTC, bjoernma commented on Station.json
> +}
Aber dann wäre doch die Klammer aus der ersten Zeile nicht geschlossen? Aber ich kanns probieren?

2022-06-26 11:23 UTC, bjoernma commented on Station.json
> +}
Ok, die zwei Commits sind eigentlich nur ein löschen und danach wiedereinfügen der letzten Zeile. Was für ein Schluckauf :D  Aber sollte ja jezt gehen...

2022-06-26 11:23 UTC, marhei approved these changes

2022-06-26 11:23 UTC, merged